version: "3.9"
services:
  api:
    build: ./api/
    ports:
      - "5000:5000"
    volumes:
      - ./api/:/work/
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/work/
      - /work/node_modules
